//swiftlint:disable function_body_length
import XCTest
@testable import CosmosKit

class RelatedArticlesViewModelTests: XCTestCase {

    func testCreate() {
        let related = RelatedArticlesWidgetData(articles:
            [ArticleSummary(title: "",
                            titleText: nil,
                            sectionTitle: "sectionTitle",
                            section: Section(name: "Section", id: "section"),
                            subSection: nil,
                            adSections: nil,
                            synopsis: "",
                            image: Image(),
                            published: 1,
                            modified: 2,
                            author: nil,
                            authors: ["tom test"],
                            publication: ArticlePublication(identifier: "test"),
                            key: 1,
                            slug: "slug",
                            shareURL: "test",
                            access: true,
                            comments: true,
                            externalUrl: nil,
                            videoCount: 0,
                            readDuration: 100,
                            contentType: nil,
                            sponsor: nil,
                            marketData: nil),
             ArticleSummary(title: "",
                            titleText: nil,
                            sectionTitle: "sectionTitle",
                            section: Section(name: "Section", id: "section"),
                            subSection: nil,
                            adSections: nil,
                            synopsis: "",
                            image: Image(),
                            published: 1,
                            modified: 2,
                            author: nil,
                            authors: ["tom test"],
                            publication: ArticlePublication(identifier: "test"),
                            key: 2,
                            slug: "slug",
                            shareURL: "test",
                            access: true,
                            comments: true,
                            externalUrl: nil,
                            videoCount: 0,
                            readDuration: 100,
                            contentType: nil,
                            sponsor: nil,
                            marketData: nil),
             ArticleSummary(title: "",
                            titleText: nil,
                            sectionTitle: "sectionTitle",
                            section: Section(name: "Section", id: "section"),
                            subSection: nil,
                            adSections: nil,
                            synopsis: "",
                            image: Image(),
                            published: 1,
                            modified: 2,
                            author: nil,
                            authors: ["tom test"],
                            publication: ArticlePublication(identifier: "test"),
                            key: 3,
                            slug: "slug",
                            shareURL: "test",
                            access: true,
                            comments: true,
                            externalUrl: nil,
                            videoCount: 0,
                            readDuration: 100,
                            contentType: nil,
                            sponsor: nil,
                            marketData: nil)
                 ],
                                                meta: RelatedArticlesMetaData(title: "More"))

        let sut = RelatedArticlesViewModel(from: related, as: .live)

        XCTAssertEqual(sut.title, "More")
        XCTAssertNotNil(sut.articles[0].publishedString)
        XCTAssertEqual(sut.articles[0].key, 1)
        XCTAssertEqual(sut.articles[1].key, 2)
        XCTAssertEqual(sut.articles[2].key, 3)
    }

    func testCreate_forEdition() {
        let related = RelatedArticlesWidgetData(articles:
            [ArticleSummary(title: "",
                            titleText: nil,
                            sectionTitle: "sectionTitle",
                            section: Section(name: "Section", id: "section"),
                            subSection: nil,
                            adSections: nil,
                            synopsis: "",
                            image: Image(),
                            published: 1,
                            modified: 2,
                            author: nil,
                            authors: ["tom test"],
                            publication: ArticlePublication(identifier: "test"),
                            key: 1,
                            slug: "slug",
                            shareURL: "test",
                            access: true,
                            comments: true,
                            externalUrl: nil,
                            videoCount: 0,
                            readDuration: 100,
                            contentType: nil,
                            sponsor: nil,
                            marketData: nil),
             ArticleSummary(title: "",
                            titleText: nil,
                            sectionTitle: "sectionTitle",
                            section: Section(name: "Section", id: "section"),
                            subSection: nil,
                            adSections: nil,
                            synopsis: "",
                            image: Image(),
                            published: 1,
                            modified: 2,
                            author: nil,
                            authors: ["tom test"],
                            publication: ArticlePublication(identifier: "test"),
                            key: 2,
                            slug: "slug",
                            shareURL: "test",
                            access: true,
                            comments: true,
                            externalUrl: nil,
                            videoCount: 0,
                            readDuration: 100,
                            contentType: nil,
                            sponsor: nil,
                            marketData: nil),
             ArticleSummary(title: "",
                            titleText: nil,
                            sectionTitle: "sectionTitle",
                            section: Section(name: "Section", id: "section"),
                            subSection: nil,
                            adSections: nil,
                            synopsis: "",
                            image: Image(),
                            published: 1,
                            modified: 2,
                            author: nil,
                            authors: ["tom test"],
                            publication: ArticlePublication(identifier: "test"),
                            key: 3,
                            slug: "slug",
                            shareURL: "test",
                            access: true,
                            comments: true,
                            externalUrl: nil,
                            videoCount: 0,
                            readDuration: 100,
                            contentType: nil,
                            sponsor: nil,
                            marketData: nil)
            ],
                                                meta: RelatedArticlesMetaData(title: "More"))

        let sut = RelatedArticlesViewModel(from: related, as: .edition)

        XCTAssertNil(sut.articles[0].publishedString)
    }

    func testFiltering() {

        let publication = TestPublication(liveDomain: "cosmos-stage-qa.appspot.com", id: "times-select")
        let pubs = [FilteredPublication(id: "bl"), FilteredPublication(id: "ft")]
        let config = CosmosConfig(publication: publication,
                              filteredPublications: pubs)
        let cosmos = Cosmos(apiConfig: config, logger: nil, errorDelegate: nil, eventDelegate: nil)
        let related = RelatedArticlesWidgetData(articles:[
            ArticleSummary(title: "",
                           titleText: nil,
                           sectionTitle: "sectionTitle",
                           section: Section(name: "Section", id: "section"),
                           subSection: nil,
                           adSections: nil,
                           synopsis: "",
                           image: Image(),
                           published: 1,
                           modified: 2,
                           author: nil,
                           authors: ["tom test"],
                           publication: ArticlePublication(identifier: "bl"),
                           key: 1,
                           slug: "slug",
                           shareURL: "test",
                           access: true,
                           comments: true,
                           externalUrl: nil,
                           videoCount: 0,
                           readDuration: 100,
                           contentType: nil,
                           sponsor: nil,
                           marketData: nil),
            ArticleSummary(title: "",
                           titleText: nil,
                           sectionTitle: "sectionTitle",
                           section: Section(name: "Section", id: "section"),
                           subSection: nil,
                           adSections: nil,
                           synopsis: "",
                           image: Image(),
                           published: 1,
                           modified: 2,
                           author: nil,
                           authors: ["tom test"],
                           publication: ArticlePublication(identifier: "ft"),
                           key: 2,
                           slug: "slug",
                           shareURL: "test",
                           access: true,
                           comments: true,
                           externalUrl: nil,
                           videoCount: 0,
                           readDuration: 100,
                           contentType: nil,
                           sponsor: nil,
                           marketData: nil),
            ArticleSummary(title: "",
                           titleText: nil,
                           sectionTitle: "sectionTitle",
                           section: Section(name: "Section", id: "section"),
                           subSection: nil,
                           adSections: nil,
                           synopsis: "",
                           image: Image(),
                           published: 1,
                           modified: 2,
                           author: nil,
                           authors: ["tom test"],
                           publication: ArticlePublication(identifier: "test"),
                           key: 3,
                           slug: "slug",
                           shareURL: "test",
                           access: true,
                           comments: true,
                           externalUrl: nil,
                           videoCount: 0,
                           readDuration: 100,
                           contentType: nil,
                           sponsor: nil,
                           marketData: nil)
        ], meta: RelatedArticlesMetaData(title: "More"))

        let sut = RelatedArticlesViewModel(from: related, as: .live)

        let articles = sut.filterArticles(cosmos: cosmos)

        XCTAssertEqual(articles.count, 1)
        XCTAssertEqual(articles.first?.key, 3)
    }
}
